---
  AWSTemplateFormatVersion: "2010-09-09"
  Description: "myvpc2"
  Parameters:
      VpcName: 
        Type: "String"
      VpcCIDR: 
        Type: "String"
      PublicSubnetACIDR: 
        Type: "String" 
      PublicSubnetBCIDR:
        Type: "String"
      PrivateSubnetACIDR:
        Type: "String"
      PrivateSubnetBCIDR:
        Type: "String"
  Resources:
    Vpc:
      Type: "AWS::EC2::VPC"
      Properties:
        EnableDnsSupport: "true"
        EnableDnsHostnames: "true"
        CidrBlock:
          Ref: "VpcCIDR"
        Tags:
          -
            Key: "Name"
            Value:
              Ref: "VpcName"
    PublicSubnetA:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId:
          Ref: "Vpc"
        CidrBlock:
          Ref: "PublicSubnetACIDR"
        MapPublicIpOnLaunch: "true"
        AvailabilityZone: !Sub "${AWS::Region}a"
        Tags:
          -
            Key: "Name"
            Value: !Join [ "-", [ !Ref "VpcName", public1a ] ]
    PrivateSubnetA:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId:
          Ref: "Vpc"
        CidrBlock:
          Ref: "PrivateSubnetACIDR"
        AvailabilityZone: !Sub "${AWS::Region}a"
        Tags:
          -
            Key: "Name"
            Value: !Join [ "-", [ !Ref "VpcName", private1a ] ]
    PublicSubnetB:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId:
          Ref: "Vpc"
        CidrBlock:
          Ref: "PublicSubnetBCIDR"
        MapPublicIpOnLaunch: "true"
        AvailabilityZone: !Sub "${AWS::Region}b"
        Tags:
          -
            Key: "Name"
            Value: !Join [ "-", [ !Ref "VpcName", public1b ] ]
    PrivateSubnetB:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId:
          Ref: "Vpc"
        CidrBlock:
          Ref: "PrivateSubnetBCIDR"
        AvailabilityZone: !Sub "${AWS::Region}b"
        Tags:
          -
            Key: "Name"
            Value: !Join [ "-", [ !Ref "VpcName", private1b ] ]
    Igw:
      Type: "AWS::EC2::InternetGateway"
      Properties:
        Tags:
          -
            Key: "Name"
            Value: !Join [ "-", [ !Ref "VpcName", igw ] ]
    IgwAttachment:
      Type: "AWS::EC2::VPCGatewayAttachment"
      Properties:
        VpcId:
          Ref: "Vpc"
        InternetGatewayId:
          Ref: "Igw"
    PublicRt:
      Type: "AWS::EC2::RouteTable"
      Properties:
        VpcId:
          Ref: "Vpc"
        Tags:
          -
            Key: "Name"
            Value: !Join [ "-", [ !Ref "VpcName", public, rt ] ]
    PublicDefaultRoute:
      Type: "AWS::EC2::Route"
      DependsOn: "IgwAttachment"
      Properties:
        RouteTableId:
          Ref: "PublicRt"
        DestinationCidrBlock: "0.0.0.0/0"
        GatewayId:
          Ref: "Igw"
    PublicRt2PublicSubnetA:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        SubnetId:
          Ref: "PublicSubnetA"
        RouteTableId:
          Ref: "PublicRt"
    PublicRt2PublicSubnetB:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        SubnetId:
          Ref: "PublicSubnetB"
        RouteTableId:
          Ref: "PublicRt" 
    PrivateRt:
      Type: "AWS::EC2::RouteTable"
      Properties:
        VpcId:
          Ref: "Vpc"
        Tags:
          -
            Key: "Name"
            Value: !Join [ "-", [ !Ref "VpcName", private, rt ] ]
    PublicRt2PrivateSubnetA:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        SubnetId:
          Ref: "PrivateSubnetA"
        RouteTableId:
          Ref: "PrivateRt"
    PublicRt2PrivateSubnetB:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        SubnetId:
          Ref: "PrivateSubnetB"
        RouteTableId:
          Ref: "PrivateRt"    
    PublicNacl:
      Type: "AWS::EC2::NetworkAcl"
      Properties:
        VpcId:
          Ref: "Vpc"
        Tags:
          -
            Key: "Name"
            Value: !Join [ "-", [ !Ref "VpcName", public, nacl ] ]
    PublicNaclInbound:
      Type: "AWS::EC2::NetworkAclEntry"
      Properties:
        NetworkAclId:
          Ref: "PublicNacl"
        RuleNumber: "100"
        Protocol: "-1"
        RuleAction: "allow"
        Egress: "false"
        CidrBlock: "0.0.0.0/0"
        PortRange:
          From: "0"
          To: "65535"
    PublicNaclOutbound:
      Type: "AWS::EC2::NetworkAclEntry"
      Properties:
        NetworkAclId:
          Ref: "PublicNacl"
        RuleNumber: "100"
        Protocol: "-1"
        RuleAction: "allow"
        Egress: "true"
        CidrBlock: "0.0.0.0/0"
        PortRange:
          From: "0"
          To: "65535"
    PublicNacl2PublicSubnetA:
      Type: "AWS::EC2::SubnetNetworkAclAssociation"
      Properties:
        SubnetId:
          Ref: "PublicSubnetA"
        NetworkAclId:
          Ref: "PublicNacl"
    PublicNacl2PublicSubnetB:
      Type: "AWS::EC2::SubnetNetworkAclAssociation"
      Properties:
        SubnetId:
          Ref: "PublicSubnetB"
        NetworkAclId:
          Ref: "PublicNacl" 
    PrivateNacl:
      Type: "AWS::EC2::NetworkAcl"
      Properties:
        VpcId:
          Ref: "Vpc"
        Tags:
          -
            Key: "Name"
            Value: !Join [ "-", [ !Ref "VpcName", private, nacl ] ]
    PrivateNaclInbound:
      Type: "AWS::EC2::NetworkAclEntry"
      Properties:
        NetworkAclId:
          Ref: "PrivateNacl"
        RuleNumber: "100"
        Protocol: "-1"
        RuleAction: "allow"
        Egress: "false"
        CidrBlock: "0.0.0.0/0"
        PortRange:
          From: "0"
          To: "65535"
    PrivateNaclOutbound:
      Type: "AWS::EC2::NetworkAclEntry"
      Properties:
        NetworkAclId:
          Ref: "PrivateNacl"
        RuleNumber: "100"
        Protocol: "-1"
        RuleAction: "allow"
        Egress: "true"
        CidrBlock: "0.0.0.0/0"
        PortRange:
          From: "0"
          To: "65535"
    PrivateNacl2PrivateSubnetA:
      Type: "AWS::EC2::SubnetNetworkAclAssociation"
      Properties:
        SubnetId:
          Ref: "PrivateSubnetA"
        NetworkAclId:
          Ref: "PrivateNacl"
    PrivateNacl2PrivateSubnetB:
      Type: "AWS::EC2::SubnetNetworkAclAssociation"
      Properties:
        SubnetId:
          Ref: "PrivateSubnetB"
        NetworkAclId:
          Ref: "PrivateNacl"
    SgAllTraffic:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allows all inbound and outbound traffic
        GroupName: !Join [ "-", [ !Ref "VpcName", sg, alltraffic ] ]
        VpcId:
          Ref: "Vpc"
        SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0		  
  Outputs:
    VpcId:
      Description: "VPC ID"
      Value:
        Ref: "Vpc"
      Export:
        Name:
          !Sub "${VpcName}-vpcid"
    PublicSubnetA:
      Description: "SubnetId of the public-a subnet"
      Value:
        Ref: "PublicSubnetA"
      Export:
        Name:
          !Sub "${VpcName}-public-a"
    PublicSubnetB:
      Description: "SubnetId of the public-b subnet"
      Value:
        Ref: "PublicSubnetB"
      Export:
        Name:
          !Sub "${VpcName}-public-b"
    PrivateSubnetA:
      Description: "SubnetId of the private-a subnet"
      Value:
        Ref: "PrivateSubnetA"
      Export:
        Name:
          !Sub "${VpcName}-private-a"
    PrivateSubnetB:
      Description: "SubnetId of the private-b subnet"
      Value:
        Ref: "PrivateSubnetB"
      Export:
        Name:
          !Sub "${VpcName}-private-b"
    PublicRt:
      Description: "Route Table Id of the Public Routing Table"
      Value:
        Ref: "PublicRt"
      Export:
        Name:
          !Sub "${VpcName}-public-rt"
    PrivateRt:
      Description: "RouteTableId of the myvpc2 Private Routing Table"
      Value:
        Ref: "PrivateRt"
      Export:
        Name:
          !Sub "${VpcName}-private-rt"
    SgAllTraffic:
      Description: "Seccurity Group Id of the All Traffic group"
      Value: { "Fn::GetAtt" : ["SgAllTraffic", "GroupId"] }
      Export:
        Name:
          !Sub "${VpcName}-sg-alltraffic"
